//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INV.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InventoryEntities : DbContext
    {
        public InventoryEntities()
            : base("name=InventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<SupplierInvoice> SupplierInvoices { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Supply> Supplies { get; set; }
        public virtual DbSet<SupplyDetail> SupplyDetails { get; set; }
    
        public virtual ObjectResult<Nullable<int>> BrandWorth(Nullable<int> brandId)
        {
            var brandIdParameter = brandId.HasValue ?
                new ObjectParameter("BrandId", brandId) :
                new ObjectParameter("BrandId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("BrandWorth", brandIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CategoryWorth(Nullable<int> catId)
        {
            var catIdParameter = catId.HasValue ?
                new ObjectParameter("CatId", catId) :
                new ObjectParameter("CatId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CategoryWorth", catIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> LowStock()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("LowStock");
        }
    
        public virtual ObjectResult<maxBrandsales_Result> maxBrandsales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<maxBrandsales_Result>("maxBrandsales");
        }
    
        public virtual ObjectResult<maxsales_Result> maxsales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<maxsales_Result>("maxsales");
        }
    
        public virtual ObjectResult<minBrandsales_Result> minBrandsales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<minBrandsales_Result>("minBrandsales");
        }
    
        public virtual ObjectResult<minsales_Result> minsales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<minsales_Result>("minsales");
        }
    
        public virtual ObjectResult<Nullable<int>> NumBrand()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("NumBrand");
        }
    
        public virtual ObjectResult<Nullable<int>> NumCat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("NumCat");
        }
    
        public virtual int NumEmp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NumEmp");
        }
    
        public virtual ObjectResult<Nullable<int>> NumOr()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("NumOr");
        }
    
        public virtual ObjectResult<Nullable<int>> NumPro()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("NumPro");
        }
    
        public virtual ObjectResult<Nullable<int>> NumSup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("NumSup");
        }
    
        public virtual ObjectResult<Nullable<int>> StockWorth()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("StockWorth");
        }
    }
}
