//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierInvoice
    {
        public int Sinv_id { get; set; }
        public int sup_id { get; set; }
        public int pro_id { get; set; }
        public string emp_id { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> UnitPrice { get; set; }
        public string Quantity { get; set; }
        public Nullable<int> Discount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
